language: java
jdk:
  - openjdk11
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: school-protocol