FROM adoptopenjdk/openjdk11:alpine-jre
ARG JAR_FILE=target/*.jar
ENV DATABASE_URL=${DATABASE_URL}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV DATABASE_USER=${DATABASE_USER}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080/tcp
