spring:
  primary:
    datasource:
      password: ${MYSQL_PASSWORD} #not shown in production environments
      username: ${DATABASE_USER}
      driver: com.mysql.cj.jdbc.Driver
      url: ${DATABASE_URL}
  replica:
    datasource:
      password: ${MYSQL_PASSWORD_REPLICA} #not shown in production environments
      username: ${DATABASE_USER_REPLICA}
      driver: com.mysql.cj.jdbc.Driver
      url: ${DATABASE_URL_REPLICA}

    #datasource:
      #password: readonlypassword #not shown in production environments
      #username: readonly
      #driver: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3307/school_protocol



